//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal_Clinic_Administration.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diseases
    {
        public int D_Id { get; set; }
        public string diagnosis { get; set; }
        public string cured { get; set; }
        public Nullable<int> P_Id { get; set; }
    
        public virtual Pet Pet { get; set; }
    }
}
